name: Test

on: workflow_dispatch

jobs:
  # Build job. Builds app for Android with Buildozer
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "install nim2"
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.x' # ex: 1.0.x, 1.2.x, 1.4.x, 2.0.x ...

      - name: install pypy3.9
        uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9' 

      - name: make python3 & pypy3 differents
        run: |
          sudo rm `which python3`
          which python3
          which pypy3

      - name: test make help
        run: |
          chmod +x make.py
          ./make.py 

      - name: tests all
        run: |
          ./make.py 3x . optimized

      - name: show stats
        run: |
          ./make.py stats . optimized

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: package
      #     path: bin/app.apk